---
title: "Test Analysis report"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: 
      version: 5
      bg: "#F9F9F9"
      fg: "#5e5ea3"
      primary: "#5e5ea3"
      base_font: !expr bslib::font_google("Lato")
      code_font: !expr bslib::font_google("JetBrains Mono")
params:
  analysis_nclusters: NA
  analysis_study_data: NA
  analysis_prevoutput: NA
  analysis_iccoutput: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(10)
library(tidyverse)
library(bslib)
library(kableExtra)
```

## *This is just a test document for now *

### Study details 
Based on the values you entered, your study had  `r params$analysis_nclusters` clusters. The number of deletions identified and the sample sizes in each cluster are shown below:

```{r}
df_final_sizes <- params$analysis_study_data

df_final_sizes %>% 
  knitr::kable("html") %>%
  kable_styling(bootstrap_options = "striped", 
                position = "left",
                full_width = F) 
```

#### Estimated prevalence plot

```{r}
prev_output <- params$analysis_prevoutput

prev_output %>% 
  ggplot() +
        geom_segment(aes(x = " ", xend = " ", y = CrI_lower/100, yend = CrI_upper/100),
                     color = "black", linewidth = 1) +
        geom_point(aes(x = " ", y = MAP/100),
                   size = 3,
                   shape = 21,
                   fill = "skyblue3") +
        geom_hline(aes(yintercept=0.05),
                   color = "darkgrey",
                   linetype = "dashed") +
        geom_text(aes(x= " ", y = 0.07, label = "5% threshold"), color = "darkgrey") +
        scale_y_continuous(labels = scales::percent_format(1), limits = c(0,1)) +
        labs(x = "",
             y = "Estimated prevalence",
             caption = paste0("Result: there is a ", ceiling(prev_output$prob_above_threshold*100), "% probability that pfhrp2 prevalence is above 5%")) +
        theme_light() +
        theme(text = element_text(size = 16))
```

#### Estimated ICC plot
```{r}
icc_output <- params$analysis_iccoutput

icc_output %>% 
  ggplot() +
        geom_segment(aes(x = " ", xend = " ", y = CrI_lower/100, yend = CrI_upper/100), 
                     color = "black", linewidth = 1) +
        geom_point(aes(x = " ", y = MAP/100), 
                   size = 4, 
                   shape = 21,
                   fill = "skyblue3") +
        scale_y_continuous(labels = scales::percent_format(1), limits = c(0,1)) +
        labs(x = "",
             y = "Estimated ICC") +
        theme_light() +
        theme(text = element_text(size = 16)) 
```